apiVersion: v1
data:
  runtime-config.yaml: |
    {}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-03-27T12:35:28Z"
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.6.7
    helm.sh/chart: loki-6.55.0
  name: loki-runtime
  namespace: monitoring
  resourceVersion: "7286"
  uid: e85a15a4-db30-4159-b19a-b1b21067b56d
